# Generated by Django 2.2.11 on 2020-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='slug',
            field=models.SlugField(default='asdf', max_length=30),
            preserve_default=False,
        ),
    ]
